### ISSUE TITLE
能不能添加个changelog？

### ISSUE THREAD

**Issue by Lupeipei** [jasl/wx_pay#100]
希望能看到changelog

**Comment by NeverMin** [comment]
对于我来说 [Commit Log](https://github.com/jasl/wx_pay/commits/master) 就够了.

**Comment by Lupeipei** [comment]
是可以，但感觉有个changelog，会更清晰些。

**Comment by jasl** [comment]
懒... 最近有一些关于多租户的需求，包括已经合并的代码可能有bug，我在跟 Rei 协商下，要不要把国内支付gem放到一个统一组织去管理

我因为不做微信平台开发，没有机会去测试了，如果有人能接手维护，也是很好的
