### ISSUE TITLE
js_code vs authorization_code

### ISSUE THREAD

**Issue by tianbymy** [jasl/wx_pay#105]
https://github.com/jasl/wx_pay/blob/98f90e97fa4b9c181a813afd41221b5ca97a0197/lib/wx_pay/service.rb#L48

**Comment by jasl** [comment]
没懂你的意思

**Comment by tianbymy** [comment]
48行 传的 js_code ,但是53行用的是：authorization_code

**Comment by jasl** [comment]
ok 我现在修一下

**Comment by jasl** [comment]
@tianbymy 已经发布了 0.20.1
