### ISSUE TITLE
rest-client 传递可选的参数

### ISSUE THREAD

**Issue by jimhj** [jasl/wx_pay#11]
https://github.com/jasl/wx_pay/blob/master/lib/wx_pay/service.rb#L56
```ruby
WxPay.extra_rest_client_options = {
  ssl_client_cert: WxPay.apiclient_cert.certificate,
  ssl_client_key: WxPay.apiclient_cert.key,
   verify_ssl: OpenSSL::SSL::VERIFY_NONE
}

 r = invoke_remote "#{GATEWAY_URL}/secapi/pay/refund", make_payload(params)
```

这样传递可选参数感觉不太好，毕竟 ssl 参数在请求其他 api的时候是不需要的，一旦执行了这里的代码以后，调用其他的api都带上这些了。

**Comment by jasl** [comment]
有什么更好方式么？其实我在考虑直接用open-uri 就是ruby的标准库来请求微信接口

**Comment by jimhj** [comment]
我觉得用rest-client挺好的，把 `extra_rest_client_options `, 提出来放在`invork_remote`里就行了，这样更灵活一点，例如
```ruby
    def self.invoke_remote(url, payload, request_options = {})
      r = RestClient::Request.execute(
        {
          method: :post,
          url: url,
          payload: payload,
          headers: { content_type: 'application/xml' }
        }.merge(request_options)
      )

  ...
```
这样请求不同的api设置不同的超时时间也更容易点

**Comment by jasl** [comment]
也可 可以给request_opts设置默认值，这样可以做到兼容
` def self.invoke_remote(url, payload, request_options = WxPay.extra_rest_client_options)`

**Comment by jimhj** [comment]
可以

**Comment by chloerei** [comment]
不要用 open-uri http://sakurity.com/blog/2015/02/28/openuri.html

简单的可以用 Net::HTTP。

**Comment by jasl** [comment]
@chloerei 等rubyconf结束 我把这阵的反馈汇总，彻底的重构一下~

**Comment by jasl** [comment]
所有API都增加了options形参，可以覆盖微信支付的账号信息、证书以及rest client的配置
