### ISSUE TITLE
调用WxPay::Service.invoke_refund，报RestClient::BadRequest (400 Bad Request)错误

### ISSUE THREAD

**Issue by 85636682** [jasl/wx_pay#111]
调用WxPay::Service.invoke_refund，报RestClient::BadRequest (400 Bad Request)错误
很奇怪的报错
尝试调试，找不到问题所在

**Comment by jasl** [comment]
400 一般是提交的参数有误，你看看最后请求的参数跟文档上的能对应不？重点看看签名这块？

**Comment by 85636682** [comment]
看了源代码，好像有部分方法，包括退款，是没签名的```params[:sign] = WxPay::Sign.generate(params)```，需要自己调用这句传入去
