### ISSUE TITLE
rest-client 总是报timeout

### ISSUE THREAD

**Issue by Wangjiaji007** [jasl/wx_pay#12]
10次里面有2次吧。
怎么破？

**Comment by jasl** [comment]
是这样，微信那边会有一些抖动，不知道你设置了多久，我之前设置5s超时，会出现一些失败，后来我取消掉timeout设置了。
你可以试下设置比较长的时间，比如10s，或者干脆取消掉

**Comment by Wangjiaji007** [comment]
我之前设置的10秒，看来只能干掉了。

**Comment by jasl** [comment]
去掉试一下吧，这一年来还没有发生过严重超时的问题，但抖动是有的
