### ISSUE TITLE
配置中的参数最好也可以做到options里面

### ISSUE THREAD

**Issue by zouchao** [jasl/wx_pay#13]
````ruby
 def self.generate_app_pay_req(params, options = {})
   params = {
     appid: options[:appid] || WxPay.appid,
     partnerid: options[:mch_id] ||WxPay.mch_id,
     package: 'Sign=WXPay',
     timestamp: Time.now.to_i.to_s
   }.merge(params)

   check_required_options(params, GENERATE_APP_PAY_REQ_REQUIRED_FIELDS)

   params[:sign] = WxPay::Sign.generate(params)

   params
 end
````
这样针对有些项目可能涉及到多个微信开发者账号，别问我为什么会有！它就是有T_T

**Comment by jasl** [comment]
好嘛... 目前也是可以覆盖的比如
`WxPay.generate_app_pay_req appid: 'xxx'` 这样应该可以的，你试试？

**Comment by zouchao** [comment]
哦哦 thx

**Comment by zouchao** [comment]
貌似证书相关的不可以的 ，证书不在这个params之类

**Comment by jasl** [comment]
好 让我考虑下

**Comment by mouse-lin** [comment]
如果不需要更改任何代码，你是需要动态更改 WxPay.appid WxPay.mch_id && WxPay.key

**Comment by jasl** [comment]
这样的话，容易串号，

```ruby
params = {
     appid: WxPay.appid,
     partnerid: WxPay.mch_id,
     package: 'Sign=WXPay',
     timestamp: Time.now.to_i.to_s
   }.merge(params)
```

这个是原始实现，意味着，只要params里提供`appid`和`partnerid` 两项后，就会覆盖原hash的默认值（即`WxPay.appid`和`WxPay.mch_id`）

**Comment by zouchao** [comment]
嗯，并不是要params而是新增一个options＝nil的参数，当然如@mouse-lin说的动态修改当然也是可以的，现在我在项目中也暂时是这样写的，但是显得gem包的扩展性不够强

**Comment by jasl** [comment]
问题本身就支持的啊...

```ruby
def self.invoke_unifiedorder(params)
      params = {
        appid: WxPay.appid,
        mch_id: WxPay.mch_id,
        nonce_str: SecureRandom.uuid.tr('-', '')
      }.merge(params)

      # blahblahblah
end
```

这是这部分函数的实现，注意这里的形参params在函数中的用法

如果这个你还不能理解的话，看这个

```
[1] pry(main)> { x:1, y:2 }
=> {:x=>1, :y=>2}
[2] pry(main)> { x:1, y:2 }.merge z: 3, x: 4
=> {:x=>4, :y=>2, :z=>3}
```

发现了华点了？

强行修改类方法的值是非常危险的方法，在某些环境下（JRuby+多线程）一定会出问题，在MRuby下这样没出事是多亏了有GIL

**Comment by zouchao** [comment]
嗯嗯，OK，你说的这个我明白了。“证书”却是不可以这样用的

**Comment by mouse-lin** [comment]
@jasl WxPay.key 这边代码也需要设置，不然签名都会出错的

```ruby
    def self.generate(params)
      query = params.sort.map do |key, value|
        "#{key}=#{value}"
      end.join('&')

      Digest::MD5.hexdigest("#{query}&key=#{WxPay.key}").upcase
    end

```

**Comment by jasl** [comment]
哦对 这倒是，忘了这块了

**Comment by jasl** [comment]
这个待我休息的时候处理下...最近工作+弄大会忙得不可开交

**Comment by mouse-lin** [comment]
@jasl :+1: 
要不我提 PR 把，Key 也是可以作为参数传入，不传入的话，就用默认的。
今年大会在深圳，又去不来了...

**Comment by jasl** [comment]
好呀~

可以参考下 <https://github.com/chloerei/alipay/blob/master/lib/alipay/service.rb#L171>
如果我做的话估摸直接搬 rei 那套吧...

**Comment by Wangjiaji007** [comment]
```     
 Digest::MD5.hexdigest("#{query}&key=#{WxPay.key}").upcase
```
这个地方改了么。。各位仁兄等你们的好消息。

**Comment by jasl** [comment]
@mouse-lin @Wangjiaji007 我已经合并了PR #8 并且向rubygems提交了0.2.0版本，来试用一下，看看能不能满足需要了。

**Comment by jasl** [comment]
我 以后™ 会重构一下代码和测试，提高一下代码质量。

**Comment by mouse-lin** [comment]
ok，:)

**Comment by jasl** [comment]
@mouse-lin 感谢！

**Comment by Wangjiaji007** [comment]
跟证书相关的配置有解决方案么？

**Comment by jasl** [comment]
@Wangjiaji007 我最近收到了很多关于这方面的建议，然而本月我没办法抽出时间来重构项目，请等10月10-11日的RubyConf China结束，我会全盘考虑下最近的反馈，然后重构项目。

**Comment by xuyao91** [comment]
证书是不是可以直接写到wx_pay.rb的配置面去更好？
