### ISSUE TITLE
证书错误

### ISSUE THREAD

**Issue by Wangjiaji007** [jasl/wx_pay#16]
```
WxPay.apiclient_cert_path
```
这个东西要写成

```
WxPay.apiclient_cert_path = File.read('path')
```
希望大家注意下

**Comment by jasl** [comment]
rubyconf结束了，待我处理完善后事宜，会重构整个项目

**Comment by jasl** [comment]
重构了版本，更新了文档
`WxPay.set_apiclient_by_pkcs12(File.read(pkcs12_filepath), pass)` 这方式来注册就好了

**Comment by BennyLcola** [comment]
ERROR -- : PKCS12_parse: mac verify failure，我现在还是会报这个错，请问是什么问题？

**Comment by DevinHe** [comment]
@BennyLcola 请问你的问题如何解决的？

**Comment by BennyLcola** [comment]
@DevinHe 把p12文件删了，再重新放上去。
