### ISSUE TITLE
通知的响应格式

### ISSUE THREAD

**Issue by teeceepee** [jasl/wx_pay#2]
在 README 中，使用下面的方式生成响应
``` ruby
render :xml => {return_code: "SUCCESS"}.to_xml(:root => 'xml')
```
但是
``` ruby
 {return_code: "SUCCESS"}.to_xml(:root => 'xml')
 => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<xml>\n  <return-code>SUCCESS</return-code>\n</xml>\n" 
```
`return_code` 变成了 `return-code` ，这样没有问题？
如果不改变横线的格式，应该使用 `:dasherize => false`
``` ruby
{return_code: "SUCCESS"}.to_xml(:root => 'xml', :dasherize => false)
 => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<xml>\n  <return_code>SUCCESS</return_code>\n</xml>\n" 
```

**Comment by jasl** [comment]
文档是来自 @ivan 的贡献，我复查了一下文档，微信的要求为 `return_code` 我会更新文档，感谢你的反馈！

PS：旧版文档中只要服务器响应200状态码，微信即认为通知成功，目前KnewOne仍然按照这个版本的协议实现，也是OK的（当然你返回一个xml的时候默认也是200状态码）。

**Comment by teeceepee** [comment]
微信支付的文档很多表述都不够清晰，只是希望第三方的SDK能通过代码和文档弥补一些。
我在测试时发现响应的格式不正确（比如按照V2版本的格式）时，微信支付的服务器端会多次发送通知，当然如果通知的实现是幂等的，对应用来说也没什么影响，只是多响应几次微信支付的请求罢了。
