### ISSUE TITLE
调用退款接口返回 RestClient::ServerBrokeConnection (Server broke connection):

### ISSUE THREAD

**Issue by beyondalbert** [jasl/wx_pay#22]
你好，调用这个退款的接口时，出现了这个异常，想问一下这个不知你那边有没有遇到过～
版本：0.4.1

**Comment by jasl** [comment]
退款这个是来自其他人的贡献，我这边自己没用过，你可以打印一下异常的堆栈么？就是Rails日志里记录的异常相关信息

**Comment by jasl** [comment]
看文档 [ServerBroke](http://www.rubydoc.info/gems/rest-client/1.6.3/RestClient/ServerBrokeConnection) 是网络相关的异常，也有可能和你的网络环境有关，针对微信，也检查一下证书之类的配置是否正确吧

**Comment by beyondalbert** [comment]
好的，这边看了一下源代码，也没有看出什么问题，这边的微信这边的配置也check过，我再看看吧

**Comment by beyondalbert** [comment]
实在不好意思，是我自己这边的证书没有设置好，打扰大神了-_-

**Comment by jasl** [comment]
没事~ 腾讯的东西如果配置不当的话，很可能会产生误导性的错误出来，当初我也是踩了不少坑

**Comment by gazeldx** [comment]
It really the perm issue.

微信支付退款时, 需要设置好证书, 否则会报错: RestClient::ServerBrokeConnection 。
设置证书的方法: 先去https://pay.weixin.qq.com/ 的 'API安全'中 下载证书。然后把证书上传到服务器上, 之后修改
initialize/wx_pay.rb，如：
`WxPay.set_apiclient_by_pkcs12(File.read("/path/to/apiclient_cert.p12"), WxPay.mch_id)`

**Comment by ybintian** [comment]
👍
