### ISSUE TITLE
'JSAPI'调用需要传入openid

### ISSUE THREAD

**Issue by OhCoder** [jasl/wx_pay#3]
按照文档上给出的params的结构，不需要传入openid也能够正确返回JSAPI的结果。但现在需要传入openid才可以正确返回，前两天还不需要传入，今天却碰到这个问题，不知道是不是微信做了变动……
![issue](https://cloud.githubusercontent.com/assets/890676/6501639/00a777b8-c356-11e4-891c-b24997e2a528.jpeg)
获取NATIVE当前不需要传入openid就能正确返回。

**Comment by jasl** [comment]
这个可能是我文档的疏忽，刚刚查了一下KO的源码，我在JSAPI方式调用的时候，提供了openid参数。
我去更新一下文档

**Comment by OhCoder** [comment]
原来如此……
回复好快，Thanks
