### ISSUE TITLE
Multi-account support !!!

### ISSUE THREAD

**Issue by lin520chong** [jasl/wx_pay#31]
Multi-account support

All functions have third argument options, you can pass appid, mch_id, key, apiclient_cert, apiclient_key as a hash.

For example

WxPay::Service::generate_app_pay_req params, {appid: 'APPID', mch_id: 'MCH_ID', key: 'KEY'}

这个地方的使用方法能说的详细点不？谢谢

**Comment by jasl** [comment]
你遇到了什么问题了么？描述一下你的需求

**Comment by ryancheung** [comment]
@jasl 我们现在有个需求：之前使用单独申请微信支付，现在需要接入js 支付功能，即公众号微信支付。因此，需要多帐号支持。

建议把类方法改成实例方法

**Comment by jasl** [comment]
@ryancheung 
现在所有的方法都应该是可以接受`options`的，在这里你可以覆盖一些设置，比如源码

```ruby
    GENERATE_JS_PAY_REQ_REQUIRED_FIELDS = [:prepayid, :noncestr]
    def self.generate_js_pay_req(params, options = {})
      check_required_options(params, GENERATE_JS_PAY_REQ_REQUIRED_FIELDS)

      params = {
        appId: options.delete(:appid) || WxPay.appid,
        package: "prepay_id=#{params.delete(:prepayid)}",
        nonceStr: params.delete(:noncestr),
        timeStamp: Time.now.to_i.to_s,
        signType: 'MD5'
      }.merge(params)

      params[:paySign] = WxPay::Sign.generate(params)
      params
    end
```

你可以传递`appid`替换默认值，调用方法类似 `generate_js_pay_req(params, appid: my_appid)`

这样是否可以满足你的需要？

**Comment by ryancheung** [comment]
@jasl 我后面发现了，现在是用这个方法解决的，谢谢提醒！

**Comment by jasl** [comment]
这个问题关了吧，如果现在的设计不能满足需要，再追加场景细节
