### ISSUE TITLE
没有微信退款查询接口

### ISSUE THREAD

**Issue by krufyliu** [jasl/wx_pay#32]
为什么没有实现微信退款查询接口呢？

**Comment by jasl** [comment]
- 退款方面的接口主要来自于热心朋友们的贡献，我自己的项目没有涉及到
- 微信支付的API自身也在不断完善中，可能刚刚才开放出来

你可以 fork 一份这个项目，实现那个接口，然后 PR 回来~

**Comment by jasl** [comment]
PR #41 已经实现
