### ISSUE TITLE
ERROR -- : PKCS12_parse: mac verify failure

### ISSUE THREAD

**Issue by BennyLcola** [jasl/wx_pay#38]
我看你说已经解决了这个问题，但是我还是会报这个错！

**Comment by jasl** [comment]
好像这个功能（我自己公司的项目并没有用到）合并进来好久好像没人提过问题。

微信的话，很多异常需要你先去检查配置是否正确（主要是指微信后台里的还有你的证书本身），否则有可能得到误导性的结果，麻烦你先确认下微信支付所有配置是否正确~

**Comment by BennyLcola** [comment]
我之前用过没问题的，后来我的代码挪了一下地方，就报这个错了，所有的配置都一样，之前可以，现在就报这个错了，找不到原因。

**Comment by jasl** [comment]
那真得麻烦你帮我提供一下改动的大概情况，这个异常感觉不像是因为你移动代码造成的，可以把完整的异常堆栈贴出来么？

**Comment by BennyLcola** [comment]
找到原因了，原来是我的p12文件坏掉了，内容为空，换了之后就可以了，谢谢你的回复。

**Comment by jasl** [comment]
那我关闭啦

**Comment by BennyLcola** [comment]
好的。

**Comment by Wangjiaji007** [comment]
证书参数里那个 pass 是什么意思啊？

**Comment by jasl** [comment]
@Wangjiaji007 证书的密码，微信的证书应该是默认有密码的
