### ISSUE TITLE
统一下单的options问题

### ISSUE THREAD

**Issue by xiaozhu0827** [jasl/wx_pay#39]
统一下单的appid, mch_id,  key放在 ```config/initializers/wx_pay.rb```里是可以正常调用起微信支付页面。清空wx_pay.rb里的数据，把数据放在`invoke_unifiedorder(params, options = {})`里，无法调起微信支付的页面。debug是报错chooseWxPay:fail.
https://github.com/jasl/wx_pay/blob/master/lib/wx_pay/service.rb
放在options里的写法是：
```ruby
result = WxPay::Service.invoke_unifiedorder(params, { appid: 'appid', mch_id: 'mch_id', key: 'key'})
```
请问下是写法错了还是gem这里的问题。

**Comment by jasl** [comment]
扫了一下代码，感觉wxpay应该没有错

你检查下在网页端调用微信支付的时候调用的js，这里也需要提供appId信息的，和你调用统一支付接口的时候一致

**Comment by xiaozhu0827** [comment]
恩，gem这里没有问题。我就放心了 。
那我到时检查再找下问题的原因。打扰了呐。

**Comment by jasl** [comment]
嗯 麻烦你再检查下浏览器调用js的支付接口的时候，提交的appId等参数是否和你服务器端调用统一支付接口时的信息一致，如果还有问题咱们在交流下看看。

**Comment by xiaozhu0827** [comment]
恩，主要就是纳闷在wx_pay.rb里可以正常调起支付，写在统一下单的options里就fail.
我过会去试试，看看输出。

**Comment by jasl** [comment]
嗯，麻烦了

**Comment by xiaozhu0827** [comment]
说来惭愧，重新看了下源码，是因为自己没有在generate里没有传key的缘故。
https://github.com/jasl/wx_pay/blob/master/lib/wx_pay/sign.rb
真是不好意思。

**Comment by jasl** [comment]
哈哈，好的~
