### ISSUE TITLE
wx_pay/service.rb 参数少了一处排序

### ISSUE THREAD

**Issue by taverngoal** [jasl/wx_pay#4]
`wx_pay/service.rb`

```ruby
def self.make_payload(params)
      "<xml>#{params.map { |k, v| "<#{k}>#{v}</#{k}>" }.join}<sign>#{WxPay::Sign.generate(params)}</sign></xml>"
end
```

`#{params.map { |k, v| "<#{k}>#{v}</#{k}>" }.join}`  你后面的 WxPay::Sign.generate 给参数排了序，但你前面的params没排

**Comment by taverngoal** [comment]
xml有无序性，但结果总是
```json
{"return_code"=>"FAIL", "return_msg"=>"签名错误"}
```

**Comment by jasl** [comment]
应该不是这个的问题，在 `wx_pay/sign.rb` 的 `generate`方法会对参数做排序
你可能需要再反复检查一下 `appid` `mch_id` 以及 `key`是否设置正确

**Comment by taverngoal** [comment]
确实是…… 商户小白给的key错了，哎。打扰了
