### ISSUE TITLE
REXML::ParseException

### ISSUE THREAD

**Issue by dekexu** [jasl/wx_pay#42]
rexml在哪里定义了？ 这玩意是个啥， 怎么就合并进来了

**Comment by jasl** [comment]
请问你指的是？代码位置在？

**Comment by jasl** [comment]
需要你提供完整的异常堆栈信息，这样才好定位

**Comment by dekexu** [comment]
不好意思 刚看见回复 file: lib/wx_pay/service.rb , line: 295  
https://github.com/jasl/wx_pay/blob/97b57535b7c3cb30762bec6af73a19ea01f255ef/lib/wx_pay/service.rb#L295

**Comment by jasl** [comment]
看了下，似乎这条rescue是不必要的，去掉了，你试试github上的最新版 `gem 'wx_pay', github: 'jasl/wx_pay'` 然后 `bundle update wx_pay` 看看master的版本有没问题。

当然，对于目前 在application里 `require 'rexml/rexml'` 应该也是OK的，可能某些流行gem引入rexml，所以这个问题鲜有人提出。

至于rexml自身嘛，这玩意是ruby stdlib里的，我读了下ActionSupport快速反序列化xml的源码，似乎没用到REXML，所以这里处理不对，也不应该异常后直接返回微信服务器返回的结果。

如果导致某些接口挂掉，那就是bug了

**Comment by dekexu** [comment]
ok 谢谢了 支付测试的碰见的问题，并未影响到线上支付 。 但是其实即使 require 'rexml/rexml' ，其实也没有REXML::ParseException，所以去掉应该是合理的。 谢谢  @jasl 花时间帮忙处理了问题！

**Comment by jasl** [comment]
发布了 0.9.1 版本，关了
