### ISSUE TITLE
显示uninitialized constant WxPay::Service::RestClient错误

### ISSUE THREAD

**Issue by beyondalbert** [jasl/wx_pay#5]
你好，正在使用你提供的gem包，感谢你的开源分享。期间遇到一个问题： uninitialized constant WxPay::Service::RestClient
我需要在lib/wx_pay/service.rb中添加：
```ruby
require 'open-uri'
# 新添加以下行
require 'rest_client'
```
才能正常的通过运行。
我的环境： ruby: 2.1.5p273
                   rails: 4.1.8
我就想问一下，这个是我这边单独的原因还是什么？

**Comment by jasl** [comment]
抱歉回复晚了，应该是Bug，`Service`应该只需要`rest-client`，其他人没有报错可能是因为 `rest-client`是比较常见的依赖已经被载入到Rails环境中。

总之，我修正了一下，并且更新版本到 `0.0.3`，你可以试一下。

感谢你的指出！
