### ISSUE TITLE
Always {"return_code"=>"FAIL", "return_msg"=>"签名错误"}

### ISSUE THREAD

**Issue by pohodnya** [jasl/wx_pay#50]
Hello, I need a problem with trade_type: NATIVE. I always get Signature error.

What can be wrong?

```ruby
def get_qr_code_url
  r = WxPay::Service.invoke_unifiedorder params
  raise r['return_msg'] if r['return_code'] == 'FAIL'
  r['code_url']
end

private
def params
  {
      body: "Payment for invoice ##{@invoice.number}",
      out_trade_no: @payment.id.to_s,
      spbill_create_ip: '127.0.0.1',
      total_fee: 1,
      notify_url: notify_url,
      trade_type: 'NATIVE'
  }
end
```

**Comment by jasl** [comment]
Hi, I suggest you confirm related configuration both on wechat administration site and your app first.

**Comment by hw676018683** [comment]
I run into same problem, finally i found param type must be right, the following is my error
```
wrong: total_amount: 1000.0
right: total_amount: 1000
```

**Comment by jasl** [comment]
you're right, I checked my work's code, the price should be presented as cent, that should be told at Wechat pay's docs.

I'm closing the issue
