### ISSUE TITLE
WxPay::Service.invoke_unifiedorder 返回的数据需要重新签名吗？

### ISSUE THREAD

**Issue by FX-HAO** [jasl/wx_pay#51]
调用`WxPay::Service.invoke_unifiedorder`， 是不是只有prepay_id是有用的？我需要自己实现重新签名? 还是已经处理好了？

**Comment by FX-HAO** [comment]
我看了下代码， 发现确实没有二次签名的实现， 然后我重新签了名， 问题就解决了。

**Comment by jasl** [comment]
你说的签名是指？

**Comment by FX-HAO** [comment]
@jasl  请求的sign是无效的， 需要自己根据请求参数再次签名。

**Comment by jasl** [comment]
@FX-HAO 我是问具体对应哪个字段？sign 的话在 <https://github.com/jasl/wx_pay/blob/master/lib/wx_pay/service.rb#L299> 这里计算的
