### ISSUE TITLE
set_apiclient_by_pkcs12 里的第二个参数pass是证书的密码吗？

### ISSUE THREAD

**Issue by TangMonk** [jasl/wx_pay#52]
如下：

```
WxPay.set_apiclient_by_pkcs12(File.read(pkcs12_filepath), pass)
```

**Comment by TangMonk** [comment]
sorry

**Comment by Janady** [comment]
可以解释一下吗？我也遇到问题，OpenSSL::PKCS12::PKCS12Error: PKCS12_parse: mac verify failure

**Comment by jasl** [comment]
是证书的密码啦，这个你要去微信支付后台，显示证书那页面查看

**Comment by TangMonk** [comment]
@Janady 是证书密码

**Comment by Janady** [comment]
@TangMonk @jasl 我没设过证书密码，商户支付里面也没找到哪里显示密码的～ 难道是32位的api key？？

**Comment by Janady** [comment]
找到了，是我的商户号，在开发文档里看到了，谢谢楼上～
