### ISSUE TITLE
添加这个 gem 之后 bundle install 就失败？

### ISSUE THREAD

**Issue by 1c7** [jasl/wx_pay#53]
![image](https://cloud.githubusercontent.com/assets/1804755/21985003/c02f2fac-dc33-11e6-9abb-9f276db03aa4.png)
不太确定是怎么回事，只要一加了这个 gem 就会失败，不加的话 bundle install 很顺畅。

![image](https://cloud.githubusercontent.com/assets/1804755/21985027/deb12ed0-dc33-11e6-9fd9-ccd75d2877e3.png)
各种方法都试了，都没有解决问题。

**Comment by jasl** [comment]
跟 `wx_pay` 没关系... 是你用了一个 gemsource 来自 `rails-assets` 的 gem，然后可能是你拼写错或者这个包在 `rails-assets` 上还没有生成，bundler 找不到所以无法继续。

**Comment by 1c7** [comment]
好的，感谢回复。
但是我没法调试出是哪里出了问题，实在没办法就参考了下 gem 里面的代码自己写了。
反正我也只需要微信公众号支付这一块。。

:D

**Comment by jasl** [comment]
就是我回复你的问题嘛，另外我不太推荐用 rails-assets
