### ISSUE TITLE
没有【企业付款API 】和【现金红包 API 】的支持？

### ISSUE THREAD

**Issue by 1c7** [jasl/wx_pay#55]
Hi
首先感谢作者写这个 gem。

另外我想确认一下，看 readme 里好像没有这俩功能，话说这俩应该还没实现对吧？
企业付款 API：
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2

普通红包 API：
https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_4&index=3

然后我近期在做这个事，主要是实现打赏功能，然后我们平台抽成一些，剩下的给用户，比如用户 A 给 B 打赏了100元，用户 B 实际到账 80元，因为我们抽了20%（暂定比例，以后肯定会下调）

我先确认下，如果没有的话，等我自己实现了我看看要不要发个 PR 融进去。

再次感谢:D

**Comment by 1c7** [comment]
另外上次 bundle install 出错的问题我知道是怎么回事了，是 Gemfile 里其他东西造成的，我发个 PR 更新下 readme 文档？然后你再修改下我写的内容？ 或者你直接根据这个写进去也行：https://github.com/jasl/wx_pay/issues/53  （看最后一个评论。

**Comment by jasl** [comment]
没实现这俩，这 gem 最核心的内容是我从过去公司的项目的工作提取的，之后的各种微信支付的接口实现就靠大伙贡献了，现在我新工作没有测试微信支付的环境，而且微信支付的接口不太好测试，你可以试一下~，应该不会复杂

**Comment by 1c7** [comment]
ok, 明白了
嗯，我试试。
