### ISSUE TITLE
小程序登录

### ISSUE THREAD

**Issue by kinders** [jasl/wx_pay#60]
可以在sevice.rb增加一个`authenticate_from_weapp`方法来支持小程序登录吗？
只需要将`authenticate`方法复制一次，将里面的`authorization_code`，改为`js_code`，应该就可以了。

**Comment by jasl** [comment]
那我过会重构下好啦

**Comment by jasl** [comment]
@kinders 你可以确认一下么？你可以在你的程序里给 wx_pay 打个补丁测试，听你意思好像要这么做？

```ruby
module WxPay
  module Service
    def self.authenticate_weapp(js_code, options = {})
      options = WxPay.extra_rest_client_options.merge(options)
      url = "https://api.weixin.qq.com/sns/oauth2/access_token?appid=#{WxPay.appid}&secret=#{WxPay.appsecret}&code=#{authorization_code}&grant_type=js_code"

      ::JSON.parse(RestClient::Request.execute(
        {
          method: :get,
          url: url
        }.merge(options)
      ), quirks_mode: true)
    end
  end
end
```

**Comment by kinders** [comment]
地址行应该是：
**url = "https://api.weixin.qq.com/sns/jscode2session?appid=#{WxPay.appid}&secret=#{WxPay.appsecret}&js_code={js_code}&grant_type=authorization_code"**


我应该开个分支，自己测试好再pull给您。
但很抱歉，我水平实在太菜，又没有机会测试。所以不敢确定自己的方式是否正确。

**Comment by jasl** [comment]
很简单的~ 
你只要在自己项目测试通了就行，代码很难搞错，主要是跟微信那边调通

**Comment by kinders** [comment]
已经在自己的项目中通过测试了。 #67

**Comment by jasl** [comment]
@kinders 昨天看到啦，这两天生病，周末看哦~

**Comment by jasl** [comment]
感谢~
