### ISSUE TITLE
WxPay::Service.invoke_unifiedorder 总是报undefined method for nil是为什么？

### ISSUE THREAD

**Issue by FoxZhao** [jasl/wx_pay#68]

**Comment by jasl** [comment]
你要把完整的异常栈信息还有调用方式（你觉得的敏感信息简单处理模糊掉）才能讨论啊。。。

**Comment by FoxZhao** [comment]
已经检查出问题，，坑货队友把我的初始化文件删了。。。

**Comment by jasl** [comment]
哈哈哈哈。。。

放心这 Gem 本来是我给公司项目写的，好多团队验证多年，所以 `invoke_unifiedorder` 这种一定会用到的接口很直接的错误通常不是 Gem 触发的啦
