### ISSUE TITLE
请问有沙箱功能么？

### ISSUE THREAD

**Issue by zhangalex** [jasl/wx_pay#70]
你好，非常感谢您提供的这个gem，请问有沙箱功能么？

**Comment by jasl** [comment]
hi 抱歉之前没看到

没有沙箱，一方面腾讯腾讯没有提供沙箱环境，另一方面腾讯也没有提供完整的请求结果文档，所以一切请以生产环境的测试结果为准

**Comment by zhangalex** [comment]
谢谢，

我不知道这个是不是我理解的支付宝的沙箱功能：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1

**Comment by jasl** [comment]
@zhangalex 看来是后加的，看样子是 URL 加 `sandboxnew` 即可，因为我现在的工作和公司都不再涉及微信支付相关的开发了，你可否测试在你的应用启动时覆盖 wxpay 内的网关地址 `WxPay::Service::GATEWAY_URL = 'https://api.mch.weixin.qq.com/sandboxnew' 然后测试这个沙箱环境是否可用？如果可以的话，我们只需要重构一下，增加一个配置去选择正式环境，还是测试环境就好了

**Comment by zhangalex** [comment]
不过不仅仅URL有所区别，沙箱的签名方式也是不同的。当前项目完成后，我会花时间完成该功能。

**Comment by jasl** [comment]
好的，感谢！
