### ISSUE TITLE
请问有实现企业付款到银行卡的接口吗？

### ISSUE THREAD

**Issue by FX-HAO** [jasl/wx_pay#78]
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=24_2

**Comment by jasl** [comment]
通过利用你发的文档里提到的 API `mmpaysptrans/pay_bank` 全局搜索 <https://github.com/jasl/wx_pay/blob/master/lib/wx_pay/service.rb> 没有找到结果，说明没有。。。

你可以参考 `service.rb` 里面的代码实现这套，然后 PR 回来

**Comment by FX-HAO** [comment]
恩， 我自己写的差不多了， 但是这个接口有两个参数需要去获取微信的公钥进行加密， 现在卡在这两个参数一直微信报给我`解密真实姓名或银行卡号出错`， 等我解决了会提个PR。

**Comment by jasl** [comment]
辛苦，感谢！
