### ISSUE TITLE
appId mch_id key 在微信开发者平台与公号是不同

### ISSUE THREAD

**Issue by mouse-lin** [jasl/wx_pay#8]
没有遇到在开发者平台（app客户端）与微信公号支付 appId、mch_id、key是不同情况么？

**Comment by jasl** [comment]
没有...如果这样子的话。。是不是取一个就可以了...

**Comment by mouse-lin** [comment]
@jasl 好像是不可以的，APP 和 NATIVE与 JSAPI是不同，会提示没支付权限，Wechat支付统一没弄好

**Comment by jasl** [comment]
那恐怕只好搞两套了。。。

**Comment by mouse-lin** [comment]
refer #13

**Comment by jasl** [comment]
哦 这个情况我们是遇到过的 你需要申请开放平台 然后通过UNION ID来解决
不过这个工作我是委派给同事完成的，我白天去和他了解一下细节吧

**Comment by jasl** [comment]
我们的场景是 微信登录和微信支付是使用服务号，然后通过微信公众号引流之后发生禁止跨号（服务号与公众号）支付，不知道和这个Issue的场景相似

**Comment by mouse-lin** [comment]
@jasl 和 app_id 与 key 这些支持多个其实是一样的，可以解决，我自己在用的 Gem 就是这样，所以 refer 过去了。
其实情况有两种：
* 和你说的一样，在 open.weixin 域名绑定 公号和第三方 APP，这个时候会返回 UNION ID，其他情况均不会，而且在这个情况下可以绑定最多10个公号，这10个公号不会出现跨号支付问题。
* 第三方公号授权，这个时候 app_id 这些会很多，根据授权方来获取

**Comment by mouse-lin** [comment]
括号支付，我现在的做法是和有赞一样的，通过二维码扫描去做，二维码扫描的话，有两种方式：一种是先有订单，另外一种是后有订单。（要注意的是 JSAPI 与 NATIVE 的 trade_no 不可以一样，不然会被提示重复下单）

**Comment by jasl** [comment]
明白了，那看来支持多号还是挺重要的。

你用的也是我的GEM吧？如果有可能的话把改进Port回来？我尽量这两天处理下，但我自己这边恐怕没有场景去测试

**Comment by mouse-lin** [comment]
@jasl 我提了PR了

**Comment by jasl** [comment]
好，我处理下
