### ISSUE TITLE
企业付款接口一直报签名错误

### ISSUE THREAD

**Issue by insub** [jasl/wx_pay#82]
检查过许多遍商户号和appid了，主要是，用 WxPay::Service.invoke_unifiedorder 是正常的，即便是用 WxPay::Service.gettransferinfo 返回得也只是无商户订单号而已，但是调用 WxPay::Service.invoke_transfer 就一直是报签名错误 "err_code"=>"SIGN_ERROR" 
......
代码如下：

```
def test
    transfer = {
      partner_trade_no: "1000000000001", 
      openid: "oQ4ww0Sl3QQzYOxJKg-dJaa6lBxs",
      check_name: "NO_CHECK",
      amount: 100,
      desc: "提现至微信零钱",
      spbill_create_ip: '127.0.0.1', 
      appid: Setting.wxa.appid
    }

    render text: WxPay::Service.invoke_transfer(transfer)
  end
```

**Comment by ohimy** [comment]
企业付款的签名用到了
商户账号appid | mch_appid
导致签名错误

**Comment by jasl** [comment]
要看下那接口是不是需要配置证书，企业相关的接口我印象里都需要配置证书的

**Comment by insub** [comment]
时间太久远，我先 close 了
