### ISSUE TITLE
我想在微信支付里动态的添加appid

### ISSUE THREAD

**Issue by a4652097** [jasl/wx_pay#87]
```
WxPay::Service.invoke_unifiedorder params, {appid: brand.wechat_setting.wechat_appid}
```
获得prepay_id和nonce_str后调用
```
WxPay::Service.generate_js_pay_req params
```

```
        "data": {
            "appId": null,
            "package": "prepay_id=wx1021284266595370252b84150536813469",
            "nonceStr": "bFU1kKQ8sZ6Z5eUe",
            "timeStamp": "1525958922",
            "signType": "MD5",
            "paySign": "FB4876D4DDB607E4B0D2BE398534F78A"
        }
```

appid是空的，导致签名错误。
有空的话能回复一下的话，十分感谢

**Comment by jasl** [comment]
可以做的，看下源码就知道了 <https://github.com/jasl/wx_pay/blob/master/lib/wx_pay/service.rb#L110>

你需要像你调用统一支付接口时候这样 `WxPay::Service.invoke_unifiedorder params, {appid: brand.wechat_setting.wechat_appid}` 去显式传 `appid`，形如 `WxPay::Service.generate_js_pay_req(params, {appid: brand.wechat_setting.wechat_appid})`

**Comment by a4652097** [comment]
看完源码后我的问题解决了，十分感谢
