### ISSUE TITLE
sse xml外部实体注入

### ISSUE THREAD

**Issue by dhyl** [jasl/wx_pay#94]
如题，最近腾讯推送了xml外部实体注入的问题。麻烦问下如何禁用外部实体注入

**Comment by jasl** [comment]
这个不清楚，是否有文档可以分享？我已经很久不做微信相关的开发了

**Comment by dhyl** [comment]
腾讯官方文档地址：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5
关于XML解析存在的安全问题指引
微信支付商户，最近暴露的XML外部实体注入漏洞(XML External Entity Injection，简称 XXE)，该安全问题是由XML组件默认没有禁用外部实体引用导致，非微信支付系统存在漏洞。

如果你在使用支付业务回调通知中，存在以下场景有使用XML解析的情况，请务必检查是否对进行了防范。

场景1：支付成功通知；
场景2：退款成功通知；
场景3：委托代扣签约、解约、扣款通知；
场景4：车主解约通知；
检查及修复建议

1.如果您的后台系统使用了官方sdk，请更新sdk到最新版本 sdk的链接:https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=11_1
2.如果您是有系统提供商，请联系提供商进行核查和升级修复；
3.如果您是自研系统，请联系技术部门按以下指引核查和修复：

XXE漏洞需要你在代码中进行相应的设置，不同语言设置的内容不同，下面提供了几种主流开发语言的设置指引：
【PHP】
libxml_disable_entity_loader(true);

【JAVA】
DocumentBuilderFactory dbf =DocumentBuilderFactory.newInstance();
dbf.setExpandEntityReferences(false);
不同java组件修复方案不一样，请参考下文【附录】中获取更多帮助 
【.Net】
XmlResolver = null;

【Python】
from lxml import etree
xmlData = etree.parse(xmlSource,etree.XMLParser(resolve_entities=False))

【c/c++(常用库为libxml2 libxerces-c)】

【libxml2】:  
确保关闭配置选项：XML_PARSE_NOENT 和 XML_PARSE_DTDLOAD
2.9版本以上已修复xxe

【libxerces-c】：
如果用的是XercesDOMParser:
XercesDOMParser *parser = new XercesDOMParser;
parser->setCreateEntityReferenceNodes(false);

如果是用SAXParser:
SAXParser* parser = new SAXParser;
parser->setDisableDefaultEntityResolution(true);

如果是用SAX2XMLReader:
SAX2XMLReader* reader = XMLReaderFactory::createXMLReader();
parser->setFeature(XMLUni::fgXercesDisableDefaultEntityResolution, true);

附录：更多开源库/语言版本的修复建议可参考：
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#C.2FC.2B.2B

**Comment by jasl** [comment]
不存在问题，WxPay 解析  XML 使用 ActiveSupport 的 XmlMini，后端默认使用 REXML，由 <https://www.ruby-forum.com/topic/6146175> 可知：

> REXML doesn't support expanding SYSTEM entity. So REXML
doesn't have vulnerability related external content.

如果你自己改用了 LibXML 作为后端，需要看下 <https://www.rubydoc.info/gems/libxml-ruby/2.3.3/LibXML/XML/Parser/Options> 来配置，并按文档说的升级到最新的 LibXml2

**Comment by dhyl** [comment]
@jasl 明白了，非常感谢你能及时回复我。
