### ISSUE TITLE
WxPay::Sign.verify? 方法在添加了 Options 的情况下会报错

### ISSUE THREAD

**Issue by insub** [jasl/wx_pay#98]
如：
`WxPay::Sign.verify?(result, {appid: 'wx9789bbd10345788', mch_id: '3609811271', key: 'L6CwQ7KBDm8DC7D4sUcX5cuyD5by7777'})`

会报：
ArgumentError in OrdersController#weixin_notify
comparison of Array with Array failed
的错误

如果Options中去掉 appid 以及 mch_id 的话则无此问题，但我目前是多账号模式，在校验时去掉 Options的话不知道是否会有影响？

**Comment by jasl** [comment]
我周末看一下~

**Comment by liurui12w** [comment]
您好 我的问题也和上面老哥类型

WxPay::Sign.verify?(result, {appid: 'wx9789bbd10345788', mch_id: '3609811271', key: 'L6CwQ7KBDm8DC7D4sUcX5cuyD5by7777'})

多账号模式
微信回调的时候  签名验证是失败

**Comment by jasl** [comment]
啊 前阵子比较忙 忘记了 看来这里是代码上有问题

我现在没有微信支付的账号密码了，这个比较尴尬，我想想办法吧。。。你们有可能的话帮debug下 估计实际问题不复杂

**Comment by liurui12w** [comment]
是的 是 sign里的校验问题，
 def self.verify?(params, options = {})
      return true if WxPay.sandbox_mode?
      params = params.dup
      params = params.merge(options)
      sign = params.delete('sign') || params.delete(:sign)
      generate(params) == sign
    end

缺少了 options.delete(:appid)

下面是我从你的service.rb 取到的代码
    def self.invoke_unifiedorder(params, options = {})
      params = {
        appid: options.delete(:appid) || WxPay.appid,
        mch_id: options.delete(:mch_id) || WxPay.mch_id,
        key: options.delete(:key) || WxPay.key,
        nonce_str: SecureRandom.uuid.tr('-', '')
      }.merge(params)


我猜想 应该是类似这样的写法  ，您在看下

**Comment by liurui12w** [comment]
@jasl 我发表了一个评论 您先看下 觉得对的话 在采纳，别轻易就合并了  如果代码有误 崩了就不好了  kkkk

**Comment by liurui12w** [comment]
wx_pay/lib/wx_pay/sign.rb
def self.verify?(params, options = {})
  return true if WxPay.sandbox_mode?
  params = params.dup
#old   params = params.merge(options)
  params = {
    appid: options.delete(:appid) || WxPay.appid,
    mch_id: options.delete(:mch_id) || WxPay.mch_id,
    key: options.delete(:key) || WxPay.key
  }.merge(params)
  sign = params.delete('sign') || params.delete(:sign)
  generate(params) == sign
end

**Comment by jasl** [comment]
@liurui12w  周末犯懒了。。。等我一会到公司看一下，你要学一下 markdown 啊...

**Comment by jasl** [comment]
@liurui12w 我把你的代码加入到最新的代码中了，如果可以的话请帮忙测试下（注意别发布到你们的生产环境哈）

**Comment by jasl** [comment]
> @jasl 刚才我测试过后 发现，单账户没问题，但是如果是多账户还会是出现问题
> 
> wx_pay/lib/wx_pay/sign.rb 原方法
> 
> ```
> def self.generate(params, sign_type = SIGN_TYPE_MD5)
>   #由于verify？方法 给params["key"]附过值后 导致下面string_sign_temp生成的字符串会多一个key 所以导致结果一直签名错误
>   key = params.delete(:key)
> 
>   query = params.sort.map do |k, v|
>     "#{k}=#{v}" if v.to_s != ''
>   end.compact.join('&')
> 
>   string_sign_temp = "#{query}&key=#{key || WxPay.key}"
> 
>   if sign_type == SIGN_TYPE_MD5
>     Digest::MD5.hexdigest(string_sign_temp).upcase
>   elsif sign_type == SIGN_TYPE_HMAC_SHA256
>     OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), key, string_sign_temp).upcase
>   else
>     warn("WxPay Warn: unknown sign_type : #{sign_type}")
>   end
> end
> ```
> 下面是我改的
> 
> ```
> def self.generate(params, sign_type = SIGN_TYPE_MD5)
>   key = params.delete(:key)
> 
>   new_key = params["key"] #after
>   key = params.delete("key") if params["key"] #after
> 
>   query = params.sort.map do |k, v|
>     "#{k}=#{v}" if v.to_s != ''
>   end.compact.join('&')
> 
>   string_sign_temp = "#{query}&key=#{key || new_key || WxPay.key}" #after
> 
>   if sign_type == SIGN_TYPE_MD5
>     Digest::MD5.hexdigest(string_sign_temp).upcase
>   elsif sign_type == SIGN_TYPE_HMAC_SHA256
>     OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), key, string_sign_temp).upcase
>   else
>     warn("WxPay Warn: unknown sign_type : #{sign_type}")
>   end
> end
> ```
> 这个效果应该是需要的下面方法 单账户多账户我都测试过了，都可以验证签名的对错，如果签名有问题的话 那就是 sign 传的key的问题了，这是我刚才试验得出的，你也可以先看下 合适在修改

明白了，那看来正确的方法是避免 `params[:key]` 和 `params["key"]` 这对重复的字段，改动应该在更上层的位置，这里也没有太漂亮的改法。

你的
```ruby
key = params.delete(:key)

new_key = params["key"] #after
key = params.delete("key") if params["key"] #after
```

看上去等价于
```ruby
key = params.delete(:key)
key = params.delete("key") if params["key"]
```

我改了一下推上去了，再麻烦确认一下吧!

**Comment by liurui12w** [comment]
@jasl 少了点东西 
 

    #这个是多账号传进来的key  需要保留 并且拼接新的sign，一定要先赋值 在清除 要么会没有传进来的key
    new_key = params["key"] #after  
    key = params.delete("key") if params["key"] #after

    # new_key 如果单账户是没有的nil 所以会使用默认的Wxpay.key，如果多账户传来key  会存在一个new_key 用来拼接sign用的
    string_sign_temp = "#{query}&key=#{key || new_key || WxPay.key}" #after new_key

**Comment by jasl** [comment]
@liurui12w 好吧 按你的方式改了

**Comment by liurui12w** [comment]
@jasl 互利关系 我刚好用这个了 就不用自己写的了，也省代码  是个挺好的gem

**Comment by jasl** [comment]
@liurui12w 周末发新版吧，我之前知道这里有问题，但是没有微信支付的账号了，搞好也没法测，所以很久都没再发新版

**Comment by jasl** [comment]
春节开工，发布 0.19.0

**Comment by 85636682** [comment]
我现在遇到一个问题，WxPay::Sign.verify? 方法在多账户情况下添加了 Options 的情况，验证结果为FAIL，但是微信返回的结果是SUCCESS的。
```
{"appid"=>"", "bank_type"=>"OTHERS", "cash_fee"=>"1", "fee_type"=>"CNY", "is_subscribe"=>"N", "mch_id"=>"1488496992", "nonce_str"=>"3a821ca8da764d23b6e7a26ab96b0b41", "openid"=>"", "out_trade_no"=>"20200220174438981", "result_code"=>"SUCCESS", "return_code"=>"SUCCESS", "sign"=>"9ED73C7EE5F5518919F09C3B68FF8A32", "time_end"=>"20200309080701", "total_fee"=>"1", "trade_type"=>"JSAPI", "transaction_id"=>"4200000511202003099072646889"}
```
麻烦看一看

**Comment by jasl** [comment]
> 我现在遇到一个问题，WxPay::Sign.verify? 方法在多账户情况下添加了 Options 的情况，验证结果为FAIL，但是微信返回的结果是SUCCESS的。
> 
> ```
> {"appid"=>"", "bank_type"=>"OTHERS", "cash_fee"=>"1", "fee_type"=>"CNY", "is_subscribe"=>"N", "mch_id"=>"1488496992", "nonce_str"=>"3a821ca8da764d23b6e7a26ab96b0b41", "openid"=>"", "out_trade_no"=>"20200220174438981", "result_code"=>"SUCCESS", "return_code"=>"SUCCESS", "sign"=>"9ED73C7EE5F5518919F09C3B68FF8A32", "time_end"=>"20200309080701", "total_fee"=>"1", "trade_type"=>"JSAPI", "transaction_id"=>"4200000511202003099072646889"}
> ```
> 
> 麻烦看一看，版本是0.20.1

微信返回结果成功，wx_pay 验证失败，估计是验证签名的时候有问题，很遗憾我现在没有可以测试微信支付的环境了...

**Comment by 85636682** [comment]
@jasl 不好意思，是我代码问题，我忘记在WxPay::Sign.verify?也要传入option了，多账户要每个方式都需要传入
