### ISSUE TITLE
GET 使用 payload 中的参数不被微信处理

### ISSUE THREAD

**Issue by ug0** [jasl/wx_pay#99]
https://github.com/jasl/wx_pay/blob/master/lib/wx_pay/service.rb#L18-L35
在 https://github.com/jasl/wx_pay/commit/2a40aa49d5aa66492360728e86840c5df3b780f6 中修改 `authenticate` 方法使用 GET 加 payload 中的参数似乎被微信忽略了，导致出错 “appid missing”。改回 URL+参数后正常。

**Comment by jasl** [comment]
你这边是如何调用的呢？

**Comment by ug0** [comment]
在微信授权并得到 code 后
调用 `WxPay::Service.authenticate(code)`

**Comment by oolzpishere** [comment]
遇到同样的问题，GET 请求加 payload 中的参数似乎被微信忽略了，导致出错 “appid missing”。
看了RestClient文档后，改成这样就正常了
```
RestClient::Request.execute(
    method: :get, 
    url: url,
    headers: {params: payload}
)

输出：
➔ GET http://example.com/resource?payload
```

**Comment by jasl** [comment]
抱歉 这个之前忘记跟进了，请问这个问题出现在目前版本的wx_pay么？是如何使用 wx_pay 导致问题触发的？

**Comment by oolzpishere** [comment]
@jasl 是滴，在最新的版本“0.19.0”，问题大概是出现在wx_pay/service.rb#authenticate的31行。
```
    def self.authenticate(authorization_code, options = {})
      options = WxPay.extra_rest_client_options.merge(options)
      payload = {
        appid: options.delete(:appid) || WxPay.appid,
        secret: options.delete(:appsecret) || WxPay.appsecret,
        code: authorization_code,
        grant_type: 'authorization_code'
      }
      url = "https://api.weixin.qq.com/sns/oauth2/access_token"

      ::JSON.parse(RestClient::Request.execute(
        {
          method: :get,
###########应该是payload这里的问题#################
          payload: payload,
          url: url
        }.merge(options)
      ), quirks_mode: true)
    end
```

调用authenticate function之后，payload的参数都配置正确了，发起RestClient::Request.execute请求，get请求是不是无法带上payload? 然后微信报错“appid missing”。appid都是设置正确了的。

**Comment by jasl** [comment]
@oolzpishere 可否提交一个PR？

**Comment by jasl** [comment]
已经发布了 0.20.0，感谢 @oolzpishere

**Comment by oolzpishere** [comment]
感谢你才是！ @jasl
